@startuml
'https://plantuml.com/class-diagram

class Grid{
    //以gridSize为单位的坐标 0,0是地图origin
    int x; 
    int y;
    int sectorID;
    uint8 cost;
    uint8 flags;
    uint16 integration;
}
Grid --*Sector

class Sector{
    //x|y
    int id; 
    //以sectorSize为单位的坐标 0,0是地图origin
    uint16 x; 
    uint16 y;
    Grid[] grids;
    int[] portalIds;
}
Sector --*Map

class PortalWindow{
    //地图生成时从0开始递增
    int id;   
    //grid为单位
    int min;
    int max;
    //grid为单位 第几列或者行
    int axis;
    bool horizonOrVertical;
}
PortalWindow --*Map

class Map{
    Vector2 origin;
    float gridSize;
    Sector[] sectors;
    PortalWindow[] portals;
    Dict<int,int> sectorIdToIndex;
    PortalGraph portalGraph;
}

class PortalNode
{
    int portalId;
    PortalNodeConnection[] connectPortals;
}

PortalNode --*PortalGraph
class PortalNodeConnection
{
    int portalId;
    int16 cost;
}
PortalNodeConnection --* PortalNode

class PortalGraph
{
    PortalNode root;
}
Map-->PortalGraph

class FlowField{
    int4 direction;
    int4 flags;
}
FlowField --* SectorFlowFields
class SectorFlowFields{
    int sectorId;
    int goalPortalId;
    FlowField[] flowFields;
}
SectorFlowFields --* FlowFieldsCache
class FlowFieldsCache
{
    Dict<long, SectorFlowFields> cache;//key:32位sectorId|32位portalId
}
@enduml